### PR TITLE
feat: Add API attractions, attraction, categories and data/data.py

### PR DESCRIPTION
**Pull request by Pinkowo**
李逸歆 / Pink

http://3.115.37.200:3000/api/attractions?page=1
http://3.115.37.200:3000/api/attractions?page=0&keyword=藝文館所
http://3.115.37.200:3000/api/attractions?page=0&keyword=北
http://3.115.37.200/:3000/api/attraction/10

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Some issues:

1. `nextPage` field of http://3.115.37.200:3000/api/attractions?page=0&keyword=%E5%8C%97 should be 1, based on our data.
2. It's much better to use `GROUP_CONCAT` and `JOIN` to combine spots and imgs tables, rather than get images one by one.

Try to solve issues and re-request review.

**Review by cwpeng — CHANGES_REQUESTED** [review]
If we use `GROUP_CONCAT` and `JOIN`, we can get attraction data and images ALL AT ONCE, DON'T need to get images one by one like your code:
```
        for xid, x in enumerate(result):
            img = db.select_imgs(xid+1)
            imgs = img[0][0].split(',')
```
So, try to implement it.

**Review by cwpeng — APPROVED** [review]
Good. Done.

**Comment by Pinkowo** [comment]
Thank you so much! Have a nice day~

**Pull request merged**
