### PR TITLE
feat: build home page(index.html) include search

### PR DESCRIPTION
**Pull request by Pinkowo**
李逸歆
http://3.115.37.200:3000/

### CODE REVIEW

**Comment by cwpeng** [comment]
You should request review explicitly from the right side in this page, so that I can review for you.

**Comment by Pinkowo** [comment]
I'm fixing a bug of /api/attractions. It works on localhost, but it fails after I pushed it on ubuntu.
Something happend on keyword. I'll figure it out.

**Review by cwpeng — APPROVED** [review]
Good. Done.

**Comment by Pinkowo** [comment]
Thank you very much. Have a lovely day! 🤩

**Pull request merged**
